import React from 'react';

function About() {
  return (
    <div className="container mt-4">
        <h1>About Us</h1>
        <p>Love For All, Hatred For None. – ...
Change the world by being yourself. – ...
Every moment is a fresh beginning. – ...
Never regret anything that made you smile. – ...
Die with memories, not dreams. – ...
Aspire to inspire before we expire.Love For All, Hatred For None. – ...
Change the world by being yourself. – ...
Every moment is a fresh beginning. – ...
Never regret anything that made you smile. – ...
Die with memories, not dreams. – ...
Aspire to inspire before we expire.  </p>

<p>Love For All, Hatred For None. – ...
Change the world by being yourself. – ...
Every moment is a fresh beginning. – ...
Never regret anything that made you smile. – ...
Die with memories, not dreams. – ...
Aspire to inspire before we expire.Love For All, Hatred For None. – ...
Change the world by being yourself. – ...
Every moment is a fresh beginning. – ...
Never regret anything that made you smile. – ...
Die with memories, not dreams. – ...
Aspire to inspire before we expire.  </p>
     
     
     </div>
  );
}

export default About;